# Changes here will be overwritten by Copier
_commit: 54cda6a
_src_path: gh:browniebroke/pypackage-template
add_me_as_contributor: false
copyright_year: '2024'
documentation: false
email: nick@koston.org
full_name: J. Nick Koston
github_username: bdraco
has_cli: false
initial_commit: true
is_django_package: false
open_source_license: MIT
package_name: freenub
project_name: freenub
project_short_description: This is a fork of pubnub when it still had an MIT license
project_slug: freenub
run_poetry_install: true
setup_github: true
setup_pre_commit: true

